---
abstract: 'Show TimeTracker status in a GTK tray applet'
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200014, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-TimeTracker-Gtk2TrayIcon
requires:
  AnyEvent: 0
  App::TimeTracker::Data::Task: 0
  App::TimeTracker::Proto: 0
  File::ShareDir: 0
  FindBin: 0
  Gtk2: 0
  Gtk2::TrayIcon: 0
  perl: 5.010
resources:
  repository: git://github.com/domm/App-TimeTracker-Gtk2TrayIcon.git
version: 1.001
